# db/models.py
from pydantic import BaseModel, Field
from typing import Dict, Any, Union

# --- User Request Model ---
class UserRequest(BaseModel):
    theme: str
    mainCharacters: int
    episodes: int
    wordsPerEpisode: str
    choicesPerEpisode: int
    tone: str
    setting: str
    audience: str
    emojis: str
    specialRequests: str
    additionalInstructions: str

# --- AI Request Model ---
class AIRequest(BaseModel):
    prompt: str
    model: str = "deepseek-reasoner"

# --- AI Response Models ---
# Model for the successful AI output (a JSON string from the LLM)
class AISuccess(BaseModel):
    response: str = Field(description="The JSON string generated by the AI.")

# Model for the error output
class AIError(BaseModel):
    error: str = Field(description="The error message if the API call failed.")

# Union type to represent the possible outcomes of the AI API call
# This is what the user_router function should expect to receive.
AIResponse = Union[AISuccess, AIError]

# --- User Response Model (The story content) ---
# Assuming the AI response is a JSON string containing a dict/object
class UserResponse(BaseModel):
    # This assumes the AI's JSON string will be parsed by the client
    # If you want to return the raw JSON object, use Dict[str, Any] or Json[Dict]
    # Here, we'll return the final structured story object.
    story_data: Dict[str, Any]